# Generated by Django 5.2.5 on 2025-11-03 11:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('quantidade', models.IntegerField(default=1)),
                ('frequencia', models.CharField(choices=[('diario', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('alvo', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
            },
        ),
        migrations.CreateModel(
            name='StatusDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('concluido', models.BooleanField(default=False)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_LyfeSync.habito')),
            ],
            options={
                'verbose_name': 'Status Diário',
                'verbose_name_plural': 'Status Diários',
                'unique_together': {('habito', 'data')},
            },
        ),
    ]
