# Generated by Django 5.2.5 on 2025-11-12 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEmailaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('verified', models.IntegerField()),
                ('primary', models.IntegerField()),
            ],
            options={
                'db_table': 'account_emailaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Usuário do Sistema (Auth)',
                'verbose_name_plural': 'Usuários do Sistema (Auth)',
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=191)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('extra_data', models.JSONField()),
            ],
            options={
                'db_table': 'socialaccount_socialaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('client_id', models.CharField(max_length=191)),
                ('secret', models.CharField(max_length=191)),
                ('key', models.CharField(max_length=191)),
                ('provider_id', models.CharField(max_length=200)),
                ('settings', models.JSONField()),
            ],
            options={
                'db_table': 'socialaccount_socialapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialappSites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'socialaccount_socialapp_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialtoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('token_secret', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socialaccount_socialtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('datanascimento', models.DateField(blank=True, db_column='dataNascimento', null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HumorTipo',
            fields=[
                ('id_tipo_humor', models.AutoField(db_column='idTipoHumor', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, unique=True, verbose_name='Nome do Estado de Humor')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição Breve')),
            ],
            options={
                'verbose_name': 'Tipo de Humor',
                'verbose_name_plural': 'Tipos de Humor',
                'db_table': 'humor_tipo',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Afirmacao',
            fields=[
                ('idafirmacao', models.AutoField(db_column='idAfirmacao', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da Afirmação')),
                ('nomeafirmacao', models.CharField(blank=True, db_column='nomeAfirmacao', max_length=100, null=True, verbose_name='Título')),
                ('descricaoafirmacao', models.TextField(blank=True, db_column='descricaoAfirmacao', null=True, verbose_name='Conteúdo')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Afirmação',
                'verbose_name_plural': 'Afirmações',
                'db_table': 'afirmacao',
            },
        ),
        migrations.CreateModel(
            name='Gratidao',
            fields=[
                ('idgratidao', models.AutoField(db_column='idGratidao', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da Gratidão')),
                ('nomegratidao', models.CharField(blank=True, db_column='nomeGratidao', max_length=100, null=True, verbose_name='Título')),
                ('descricaogratidao', models.TextField(blank=True, db_column='descricaoGratidao', null=True, verbose_name='Descrição')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Gratidão',
                'verbose_name_plural': 'Gratidões',
                'db_table': 'gratidao',
            },
        ),
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Hábito')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim (Opcional)')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Meta de Quantidade')),
                ('frequencia', models.CharField(max_length=10, verbose_name='Frequência')),
                ('alvo', models.CharField(blank=True, max_length=200, verbose_name='Alvo / Unidade de Medida')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Hábito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'db_table': 'app_lyfesync_habito',
            },
        ),
        migrations.CreateModel(
            name='Dicas',
            fields=[
                ('idDica', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Dica')),
                ('nomeDica', models.CharField(max_length=200, verbose_name='Nome da Dica')),
                ('descricaoDica', models.TextField(help_text='O conteúdo completo da dica, podendo incluir listas ou parágrafos.', verbose_name='Descrição da Dica')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('humor_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicas', to='app_LyfeSync.humortipo', verbose_name='Humor Relacionado')),
            ],
            options={
                'verbose_name': 'Dica de Humor',
                'verbose_name_plural': 'Dicas de Humor',
                'db_table': 'dicas',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], default='Cliente', max_length=15, verbose_name='Tipo de Usuário')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('idrelatorio', models.AutoField(db_column='idRelatorio', primary_key=True, serialize=False)),
                ('tiporelatorio', models.CharField(blank=True, db_column='tipoRelatorio', max_length=50, null=True, verbose_name='Tipo de Relatório')),
                ('dados', models.TextField(blank=True, help_text='Dados brutos ou serializados do relatório', null=True)),
                ('caminhoarquivo', models.TextField(blank=True, db_column='caminhoArquivo', null=True, verbose_name='Caminho do Arquivo (URL/Path)')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'relatorio',
            },
        ),
        migrations.CreateModel(
            name='Humor',
            fields=[
                ('idhumor', models.AutoField(db_column='idHumor', primary_key=True, serialize=False)),
                ('data', models.DateField(help_text='A data em que o humor foi registrado.', verbose_name='Data do Registro')),
                ('descricaohumor', models.TextField(blank=True, db_column='descricaoHumor', help_text='Opcional: Descreva o que motivou este humor.', max_length=500, null=True, verbose_name='Descrição do Humor')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Momento do Registro')),
                ('idusuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='registros_humor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_diarios', to='app_LyfeSync.humortipo', verbose_name='Estado de Humor')),
            ],
            options={
                'verbose_name': 'Registro de Humor',
                'verbose_name_plural': 'Registros de Humor',
                'db_table': 'humor',
                'ordering': ['-data'],
                'unique_together': {('idusuario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='StatusDiario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data do Registro')),
                ('concluido', models.BooleanField(verbose_name='Concluído')),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_diarios', to='app_LyfeSync.habito', verbose_name='Hábito Relacionado')),
            ],
            options={
                'verbose_name': 'Status Diário',
                'verbose_name_plural': 'Status Diários',
                'db_table': 'app_lyfesync_statusdiario',
                'unique_together': {('habito', 'data')},
            },
        ),
    ]
