# Generated by Django 5.2.5 on 2025-11-12 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='idusuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habito',
            name='alvo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alvo/Objetivo'),
        ),
        migrations.AlterField(
            model_name='habito',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='habito',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='habito',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada'),
        ),
        migrations.AlterField(
            model_name='habito',
            name='frequencia',
            field=models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('PERSONALIZADO', 'Personalizado')], default='DIARIO', max_length=20, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='habito',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade/Meta'),
        ),
    ]
