# Generated by Django 5.2.5 on 2025-11-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0002_accountemailaddress_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habito',
            old_name='meta_diaria',
            new_name='quantidade',
        ),
    ]
