# Generated by Django 5.2.5 on 2025-11-12 23:10

from django.db import migrations

# Importa as operações do Django
from django.db import migrations

# Dados de humor a serem carregados: (estado, icone, descricao)
HUMOR_TIPOS_INICIAIS = [
    ('Feliz', 'img/icon/feliz.png', 'Feliz'),
    ('Calmo', 'img/icon/calmo.png', 'Calmo'),
    ('Ansioso', 'img/icon/ansioso.png', 'Ansioso'),
    ('Triste', 'img/icon/triste.png', 'Triste'),
    ('Irritado', 'img/icon/raiva.png', 'Irritado'),
]

def carregar_humor_tipos(apps, schema_editor):
    """
    Cria ou atualiza os objetos HumorTipo iniciais.
    Esta função é idempotente (segura para rodar múltiplas vezes).
    """
    # Pega o modelo HumorTipo no estado em que estava nesta migração
    HumorTipo = apps.get_model('app_LyfeSync', 'HumorTipo')
    
    for estado, icone, descricao in HUMOR_TIPOS_INICIAIS:
        # Tenta buscar pelo estado (que deve ser único)
        obj, created = HumorTipo.objects.update_or_create(
            estado=estado,
            defaults={
                'icone': icone, 
                'descricao': descricao
            }
        )
        if created:
            print(f"Tipo de Humor '{estado}' criado.")
        else:
            print(f"Tipo de Humor '{estado}' atualizado.")

def reverter_humor_tipos(apps, schema_editor):
    """
    Remove os objetos HumorTipo criados, se existirem.
    """
    HumorTipo = apps.get_model('app_LyfeSync', 'HumorTipo')
    for estado, _, _ in HUMOR_TIPOS_INICIAIS:
        try:
            HumorTipo.objects.get(estado=estado).delete()
            print(f"Tipo de Humor '{estado}' removido.")
        except HumorTipo.DoesNotExist:
            pass # Ignora se já tiver sido apagado


class Migration(migrations.Migration):

    dependencies = [
        # Certifique-se de que a última migração de esquema seja a dependência correta
        ('app_LyfeSync', '0002_habito_idusuario_alter_habito_alvo_and_more'), 
    ]

    operations = [
        # Adiciona a operação de RunPython para carregar os dados
        migrations.RunPython(carregar_humor_tipos, reverter_humor_tipos),
    ]