# Generated by Django 5.2.5 on 2025-11-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_LyfeSync", "0002_alter_dicas_criado_por"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gratidao",
            name="nomegratidao",
        ),
    ]
