# Generated by Django 5.2.5 on 2025-11-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0003_rename_meta_diaria_habito_quantidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicas',
            options={'managed': False, 'verbose_name': 'Dica', 'verbose_name_plural': 'Dicas'},
        ),
    ]
