# Generated by Django 5.2.5 on 2025-11-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_LyfeSync", "0003_remove_gratidao_nomegratidao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="afirmacao",
            name="nomeafirmacao",
        ),
    ]
