# Generated by Django 5.2.5 on 2025-11-13 00:09

# Importações necessárias
from django.db import migrations

# Dados de Dicas (Organizados por Humor_relacionado_id)
# 1: Feliz, 2: Calmo, 3: Ansioso, 4: Triste, 5: Zangado
INITIAL_DICAS = [
    # Humor ID 1 (Feliz)
    {'humor_relacionado_id': 1, 'nomeDica': 'Compartilhe sua alegria', 'descricaoDica': 'Ligue para um amigo ou familiar para contar a novidade ou simplesmente ter uma conversa leve e divertida.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Imortalize o momento', 'descricaoDica': 'Tire uma foto ou escreva um parágrafo no seu diário sobre o que o está fazendo sentir-se tão bem.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Faça um "favor futuro"', 'descricaoDica': 'Organize ou limpe uma pequena área (como a sua secretária ou a loiça) para que o seu "eu futuro" se sinta grato.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Ouça música animada', 'descricaoDica': 'Crie uma playlist de celebração e dance um pouco.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Permita-se um prazer', 'descricaoDica': 'Desfrute do seu snack favorito ou beba uma bebida especial.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Passe tempo ao ar livre', 'descricaoDica': 'Faça uma caminhada e aprecie a natureza, absorvendo a energia do sol e do ambiente.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Defina uma meta positiva', 'descricaoDica': 'Use esta energia para iniciar um projeto ou planear uma atividade emocionante.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Pratique a gratidão', 'descricaoDica': 'Pare e reflita sobre 3 coisas pelas quais está especificamente grato neste momento.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Vista algo que o faça sentir-se bem', 'descricaoDica': 'Escolha a sua roupa favorita para prolongar o bom humor.'},
    {'humor_relacionado_id': 1, 'nomeDica': 'Conecte-se com um hobby', 'descricaoDica': 'Dedique 30 minutos a uma atividade que adora, como pintar, tocar um instrumento ou ler, e sinta o prazer de fazê-la.'},

    # Humor ID 2 (Calmo)
    {'humor_relacionado_id': 2, 'nomeDica': 'Meditação prolongada', 'descricaoDica': 'Use o tempo para uma sessão de meditação mais longa, concentrando-se na sua respiração.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Leia um livro cativante', 'descricaoDica': 'Enrole-se num cobertor e mergulhe completamente num livro, sem pressa.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Tome um banho relaxante', 'descricaoDica': 'Encha a banheira com sais, óleos essenciais (como alfazema) e acenda uma vela.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Escreva num diário de pensamentos', 'descricaoDica': 'Anote os seus sentimentos e pensamentos, aproveitando a clareza mental para se auto-refletir.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Beba chá de ervas', 'descricaoDica': 'Prepare uma chávena de chá sem cafeína (camomila ou hortelã-pimenta) e saboreie-o lentamente.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Desligue a tecnologia', 'descricaoDica': 'Passe uma hora sem ecrãs, silenciando as notificações para manter a tranquilidade.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Organize o seu espaço', 'descricaoDica': 'Arrumar e organizar pequenas áreas de forma metódica pode ser uma atividade calmante.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Faça alongamentos suaves ou Yoga Yin', 'descricaoDica': 'Movimentos lentos e focados ajudam a manter o corpo e a mente em harmonia.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Observe a natureza', 'descricaoDica': 'Sente-se junto a uma janela ou ao ar livre e observe atentamente o movimento das nuvens ou a vida das plantas e pássaros.'},
    {'humor_relacionado_id': 2, 'nomeDica': 'Abrace o ócio', 'descricaoDica': 'Permita-se não fazer absolutamente nada por um período de tempo, apenas relaxar e ser.'},

    # Humor ID 3 (Ansioso)
    {'humor_relacionado_id': 3, 'nomeDica': 'Regra 5-4-3-2-1 (Aterramento)', 'descricaoDica': 'Identifique 5 coisas que pode ver, 4 coisas que pode tocar, 3 coisas que pode ouvir, 2 coisas que pode cheirar e 1 coisa que pode saborear.'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Respire profundamente (Contagem 4-7-8)', 'descricaoDica': 'Inspire contando até 4, segure por 7, expire contando até 8. Repita 5 vezes.'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Movimento rítmico', 'descricaoDica': 'Faça uma caminhada rápida ou jogging curto para libertar o excesso de energia.'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Beba água fria', 'descricaoDica': 'Beber um copo de água gelada pode dar um pequeno "choque" ao seu sistema nervoso e focar a sua atenção.'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Organize uma lista de tarefas', 'descricaoDica': 'Escreva todos os seus pensamentos numa lista e separe as tarefas em categorias "urgente" e "pode esperar" para clarear a mente.'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Distraia-se ativamente', 'descricaoDica': 'Jogue um jogo que exija concentração mental (como Sudoku ou um puzzle).'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Escreva numa folha de "preocupações"', 'descricaoDica': 'Descarregue todas as suas preocupações para uma folha de papel e, depois, guarde-a ou descarte-a simbolicamente.'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Aperte algo', 'descricaoDica': 'Segure um objeto macio ou uma bola anti-stress e aperte com força para libertar tensão física.'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Aromaterapia', 'descricaoDica': 'Cheire óleos essenciais calmantes (como alfazema ou sândalo) diretamente do frasco ou use um difusor.'},
    {'humor_relacionado_id': 3, 'nomeDica': 'Conexão social rápida', 'descricaoDica': 'Envie uma mensagem de texto rápida a um ente querido ou faça uma breve chamada para obter apoio e sentir-se menos isolado.'},

    # Humor ID 4 (Triste)
    {'humor_relacionado_id': 4, 'nomeDica': 'Permita-se chorar', 'descricaoDica': 'Não reprima as lágrimas. Deixe-as sair, pois o choro é uma forma natural de o corpo libertar emoções.'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Enrole-se num cobertor macio', 'descricaoDica': 'Busque conforto físico com tecidos macios, cobertores quentes e roupas confortáveis.'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Assista a algo nostálgico/confortável', 'descricaoDica': 'Veja um filme infantil favorito ou uma série que já viu muitas vezes.'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Beba algo quente e reconfortante', 'descricaoDica': 'Uma sopa, um chocolate quente ou um chá de ervas.'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Dê a si mesmo um abraço', 'descricaoDica': 'Enrole os braços em torno de si e balance suavemente.'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Peça ou prepare a sua comida de conforto', 'descricaoDica': 'Coma algo que o faça sentir-se seguro e confortável (sem culpa).'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Escreva uma carta de auto-compaixão', 'descricaoDica': 'Escreva para si mesmo como se fosse o seu melhor amigo, oferecendo bondade e compreensão.'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Curta exposição solar', 'descricaoDica': 'Sente-se à janela ou no exterior por 10 minutos para absorver alguma vitamina D e luminosidade.'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Ouça música melancólica (com limite)', 'descricaoDica': 'Permita-se sentir a emoção com música, mas defina um alarme para mudar para algo mais neutro ou edificante depois de 20 minutos.'},
    {'humor_relacionado_id': 4, 'nomeDica': 'Abrace um animal de estimação ou objeto', 'descricaoDica': 'O toque suave pode ser incrivelmente reconfortante.'},

    # Humor ID 5 (Zangado)
    {'humor_relacionado_id': 5, 'nomeDica': 'Dê um soco numa almofada', 'descricaoDica': 'Use este método seguro para libertar fisicamente a frustração.'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Faça exercícios vigorosos', 'descricaoDica': 'Corra, salte, faça polichinelos ou vá ao ginásio para descarregar a adrenalina.'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Conte e respire', 'descricaoDica': 'Conte lentamente até 10 (ou até 50, se necessário) enquanto se concentra na sua respiração.'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Grite ou cante alto (num local seguro)', 'descricaoDica': 'Coloque música rock ou algo intenso no carro ou no chuveiro e cante/grite com toda a força.'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Faça uma pausa', 'descricaoDica': 'Afaste-se da fonte da sua irritação por pelo menos 15 minutos (saia da sala, da casa, etc.).'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Limpe ou organize algo intensamente', 'descricaoDica': 'Use esta energia para esfregar o chão, limpar o frigorífico ou arrumar a bagunça de forma focada e física.'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Esmague gelo ou desfie papel', 'descricaoDica': 'A destruição controlada de itens inofensivos pode ser uma excelente libertação de energia.'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Beba chá de hortelã-pimenta', 'descricaoDica': 'O seu sabor forte e estimulante pode ajudar a quebrar o ciclo de ruminação da raiva.'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Lave o rosto com água fria', 'descricaoDica': 'O choque da água fria no rosto pode ajudar a "reiniciar" o seu sistema e a acalmar a sua frequência cardíaca.'},
    {'humor_relacionado_id': 5, 'nomeDica': 'Desenhe ou rabisque com força', 'descricaoDica': 'Use canetas escuras e faça traços fortes no papel para expressar a sua raiva sem palavras.'},
]

def add_initial_dicas(apps, schema_editor):
    """Insere todas as dicas iniciais no banco de dados."""
    # Substitua 'app_LyfeSync' pelo nome real da sua app e 'Dicas' pelo nome real do modelo.
    Dicas = apps.get_model('app_LyfeSync', 'Dicas')
    
    for data in INITIAL_DICAS:
        # Se você estiver usando um ForeignKey, certifique-se de que o objeto Humor com o ID correspondente exista.
        # Aqui, estamos a assumir que o campo no modelo é um IntegerField chamado humor_relacionado_id ou que o campo
        # de chave estrangeira aceita diretamente o ID, ou que é resolvido pelo Django.
        # Se for um ForeignKey, deve ser Dicas.objects.create(humor_relacionado_id=Humor.objects.get(pk=data['humor_relacionado_id']), ...)
        # Mas para simplificar a migração de dados, usamos o ID diretamente.
        Dicas.objects.create(**data)

def remove_initial_dicas(apps, schema_editor):
    """Remove todas as dicas inseridas, útil para rollback."""
    # Substitua 'app_LyfeSync' pelo nome real da sua app e 'Dicas' pelo nome real do modelo.
    Dicas= apps.get_model('app_LyfeSync', 'Dicas')
    
    # Remove apenas as dicas que correspondem à nossa lista inicial (para evitar apagar dados criados pelo usuário)
    for data in INITIAL_DICAS:
        Dicas.objects.filter(
            humor_relacionado_id=data['humor_relacionado_id'],
            nomeDica=data['nomeDica']
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0003_auto_20251112_2310'),
    ]

    operations = [
        migrations.RunPython(add_initial_dicas, remove_initial_dicas),
    ]