# Generated by Django 5.2.5 on 2025-11-03 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0004_alter_dicas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='humor',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 11, 3), verbose_name='Momento do Registro'),
            preserve_default=False,
        ),
    ]
