# Generated by Django 5.2.5 on 2025-11-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_LyfeSync", "0004_remove_afirmacao_nomeafirmacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="afirmacao",
            name="data_registro",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Data Registro"
            ),
        ),
        migrations.AddField(
            model_name="gratidao",
            name="data_registro",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Data Registro"
            ),
        ),
    ]
