# Generated by Django 5.2.5 on 2025-11-29 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_LyfeSync", "0005_afirmacao_data_registro_gratidao_data_registro"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Chave de Configuração",
                    ),
                ),
                ("value", models.TextField(verbose_name="Valor da Configuração")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        max_length=20,
                        verbose_name="Tipo de Dado",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=255, verbose_name="Ação Realizada"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Carimbo de Data/Hora"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Detalhes adicionais da ação em formato JSON.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Atividade",
                "verbose_name_plural": "Registros de Atividades",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ExternalIntegrationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da API/Serviço"
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(
                        help_text="Armazene chaves e tokens de forma segura e criptografada.",
                        verbose_name="Chave de API (Criptografada)",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Ativo")),
                (
                    "last_synced",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Sincronização"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Integração Externa",
                "verbose_name_plural": "Configurações de Integrações Externas",
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Token de Dispositivo"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        default="web",
                        max_length=10,
                        verbose_name="Tipo de Dispositivo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Utilização"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Dispositivo",
                "verbose_name_plural": "Tokens de Dispositivo",
                "unique_together": {("user", "token")},
            },
        ),
    ]
