# Generated by Django 5.2.5 on 2025-11-03 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0005_humor_data_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humor',
            options={'ordering': ['-data'], 'verbose_name': 'Registro de Humor', 'verbose_name_plural': 'Registros de Humor'},
        ),
        migrations.AlterField(
            model_name='humor',
            name='data',
            field=models.DateField(default='2025-01-01', help_text='A data em que o humor foi registrado.', verbose_name='Data do Registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humor',
            name='descricaohumor',
            field=models.TextField(blank=True, db_column='descricaoHumor', help_text='Opcional: Descreva o que motivou este humor.', max_length=500, null=True, verbose_name='Descrição do Humor'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='estado',
            field=models.CharField(choices=[('Feliz', '😀 Feliz'), ('Calmo', '😌 Calmo'), ('Ansioso', '😟 Ansioso'), ('Triste', '😥 Triste'), ('Irritado', '😡 Irritado')], default='Calmo', max_length=10, verbose_name='Estado de Humor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humor',
            name='idusuario',
            field=models.ForeignKey(db_column='idUsuario', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='humor',
            unique_together={('idusuario', 'data')},
        ),
    ]
