# Generated by Django 5.2.5 on 2025-11-06 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0006_alter_humor_options_alter_humor_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicaHumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Feliz', 'Feliz'), ('Calmo', 'Calmo'), ('Ansioso', 'Ansioso'), ('Triste', 'Triste'), ('Irritado', 'Irritado')], default='Feliz', max_length=50, verbose_name='Humor Relacionado')),
                ('nome_dica', models.CharField(max_length=200, verbose_name='Nome da Dica')),
                ('descricao', models.TextField(help_text='O conteúdo completo da dica, podendo incluir listas ou parágrafos.', verbose_name='Descrição da Dica')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Dica de Humor',
                'verbose_name_plural': 'Dicas de Humor',
                'db_table': 'dicas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dicas',
            options={},
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], default='Cliente', max_length=15, verbose_name='Tipo de Usuário')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
