# Generated by Django 5.2.5 on 2025-11-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0007_dicahumor_alter_dicas_options_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicas',
            name='descricaodica',
        ),
        migrations.RemoveField(
            model_name='dicas',
            name='nomedica',
        ),
        migrations.RemoveField(
            model_name='dicas',
            name='tipohumor',
        ),
        migrations.AlterModelTable(
            name='dicas',
            table=None,
        ),
    ]
