# Generated by Django 5.2.5 on 2025-11-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0008_remove_dicas_descricaodica_remove_dicas_nomedica_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DicaHumor',
        ),
        migrations.AlterModelOptions(
            name='dicas',
            options={'managed': False, 'verbose_name': 'Dica de Humor', 'verbose_name_plural': 'Dicas de Humor'},
        ),
    ]
