# Generated by Django 5.2.5 on 2025-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0009_delete_dicahumor_alter_dicas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humor',
            name='estado',
            field=models.CharField(choices=[('Feliz', 'Feliz'), ('Calmo', 'Calmo'), ('Ansioso', 'Ansioso'), ('Triste', 'Triste'), ('Irritado', 'Irritado')], max_length=10, verbose_name='Estado de Humor'),
        ),
        migrations.AlterModelTable(
            name='dicas',
            table='dicas',
        ),
    ]
