# Generated by Django 5.2.5 on 2025-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LyfeSync', '0010_alter_humor_estado_alter_dicas_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humor',
            name='estado',
            field=models.CharField(choices=[('', 'Selecione🔽'), ('Feliz', 'Feliz'), ('Calmo', 'Calmo'), ('Ansioso', 'Ansioso'), ('Triste', 'Triste'), ('Irritado', 'Irritado')], max_length=10, verbose_name='Estado de Humor'),
        ),
    ]
